---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker images
        run: docker compose build
      - name: Start containers
        run: docker compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check database logs
        run: docker compose logs db
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py test"
      - name: Stop containers
        if: always()
        run: docker compose down