---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker images
        run: docker compose build
      - name: Start containers
        run: docker compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check database logs
        run: docker compose logs db
      - name: Wait for database
        run: |
          max_retries=60
          counter=0
          until docker compose exec -T db pg_isready -h localhost -p 5432 -U postgres || [ $counter -eq $max_retries ]
          do
            sleep 2
            ((counter++))
            echo "Waiting for database... (Attempt $counter/$max_retries)"
            docker compose logs db
          done
          if [ $counter -eq $max_retries ]; then
            echo "Database failed to start in time"
            exit 1
          fi
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py test"
      - name: Stop containers
        if: always()
        run: docker compose down